#!/usr/bin/env bash
# _modules/scripts/migrate_options.sh
# THIS SCRIPT IS DESIGNED TO BE RUNNING BY MAILCOW SCRIPTS ONLY!
# DO NOT, AGAIN, NOT TRY TO RUN THIS SCRIPT STANDALONE!!!!!!

migrate_config_options() {

  sed -i --follow-symlinks '$a\' chertmail.conf

  KEYS=(
    SOLR_HEAP
    SKIP_SOLR
    SOLR_PORT
    FLATCURVE_EXPERIMENTAL
    DISABLE_IPv6
    ACME_CONTACT
  )

  for key in "${KEYS[@]}"; do
    if grep -q "${key}" chertmail.conf; then
      case "${key}" in
        SOLR_HEAP)
          echo "Removing ${key} in chertmail.conf"
          sed -i '/# Solr heap size in MB\b/d' chertmail.conf
          sed -i '/# Solr is a prone to run\b/d' chertmail.conf
          sed -i '/SOLR_HEAP\b/d' chertmail.conf
          ;;
        SKIP_SOLR)
          echo "Removing ${key} in chertmail.conf"
          sed -i '/\bSkip Solr on low-memory\b/d' chertmail.conf
          sed -i '/\bSolr is disabled by default\b/d' chertmail.conf
          sed -i '/\bDisable Solr or\b/d' chertmail.conf
          sed -i '/\bSKIP_SOLR\b/d' chertmail.conf
          ;;
        SOLR_PORT)
          echo "Removing ${key} in chertmail.conf"
          sed -i '/\bSOLR_PORT\b/d' chertmail.conf
          ;;
        FLATCURVE_EXPERIMENTAL)
          echo "Removing ${key} in chertmail.conf"
          sed -i '/\bFLATCURVE_EXPERIMENTAL\b/d' chertmail.conf
          ;;
        DISABLE_IPv6)
          echo "Migrating ${key} to ENABLE_IPv6 in chertmail.conf"
          local old=$(grep '^DISABLE_IPv6=' "chertmail.conf" | cut -d'=' -f2)
          local new
          if [[ "$old" == "y" ]]; then
            new="false"
          else
            new="true"
          fi
          sed -i '/^DISABLE_IPv6=/d' "chertmail.conf"
          echo "ENABLE_IPV6=$new" >> "chertmail.conf"
          ;;
        ACME_CONTACT)
          echo "Deleting obsoleted ${key} in chertmail.conf"
          sed -i '/^# Lets Encrypt registration contact information/d' chertmail.conf
          sed -i '/^# Optional: Leave empty for none/d' chertmail.conf
          sed -i '/^# This value is only used on first order!/d' chertmail.conf
          sed -i '/^# Setting it at a later point will require the following steps:/d' chertmail.conf
          sed -i '/^# https:\/\/docs.mailcow.email\/troubleshooting\/debug-reset_tls\//d' chertmail.conf
          sed -i '/^ACME_CONTACT=.*/d' chertmail.conf
          sed -i '/^#ACME_CONTACT=.*/d' chertmail.conf
          ;;
      esac
    fi
  done

  solr_volume=$(docker volume ls -qf name=^${COMPOSE_PROJECT_NAME}_solr-vol-1)
  if [[ -n $solr_volume ]]; then
    echo -e "\e[34mSolr has been replaced within mailcow since 2025-01.\nThe volume $solr_volume is unused.\e[0m"
    sleep 1
    if [ ! "$FORCE" ]; then
      read -r -p "Remove $solr_volume? [y/N] " response
      if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
        echo -e "\e[33mRemoving $solr_volume...\e[0m"
        docker volume rm $solr_volume || echo -e "\e[31mFailed to remove. Remove it manually!\e[0m"
        echo -e "\e[32mSuccessfully removed $solr_volume!\e[0m"
      else
        echo -e "Not removing $solr_volume. Run \`docker volume rm $solr_volume\` manually if needed."
      fi
    else
      echo -e "\e[33mForce removing $solr_volume...\e[0m"
      docker volume rm $solr_volume || echo -e "\e[31mFailed to remove. Remove it manually!\e[0m"
      echo -e "\e[32mSuccessfully removed $solr_volume!\e[0m"
    fi
  fi

  # Delete old fts.conf before forced switch to flatcurve to ensure update is working properly
  FTS_CONF_PATH="${SCRIPT_DIR}/data/conf/dovecot/conf.d/fts.conf"
  if [[ -f "$FTS_CONF_PATH" ]]; then
    if grep -q "Autogenerated by mailcow" "$FTS_CONF_PATH"; then
      rm -rf $FTS_CONF_PATH
    fi
  fi
}