blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.chertmail.com/
    about: Please check the documentation for answers to common questions
  - name: Report a security vulnerability
    url: https://github.com/alholan/chertmail/security/advisories/new
    about: Please give us appropriate time to verify, respond and fix before disclosure.
